version: "3"
services:
  front:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes:
      - ./:/var/www
    command: bash -c "yarn && yarn dev"
    ports:
      - "8080:8080"
    # 環境変数の読み込み
    env_file:
      - .env.local