import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useFetchMyFeedbacks } from "../src/features/feedback/hooks/feedbacks"
import { useFetchShares } from "../src/features/share/hooks"
import { useFetchAnswers } from "../src/features/answer/hooks"

export default function Home() {
  const { feedbacks } = useFetchMyFeedbacks()
  const { answers } = useFetchAnswers()
  const { shares } = useFetchShares()

  return (
    <>
      <Head>
        <title>Cross Coaching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="">
          <div>Your answers count: {answers.length}</div>
          <div>Your feedbacks count: {feedbacks.length}</div>
          <div>Your shares count: {shares.length}</div>
        </div>
      </main>
    </>
  )
}
