import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from "@mui/material"

import { signOut } from "firebase/auth"
import { useRouter } from "next/router"
import { auth } from "../initFirebase"


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const handleLogout = async () => {
    await signOut(auth)
    await router.push("/login")
  }
  return (
    <>
      <Head>
        <title>Cross Coaching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            src="/crosscoaching_white_logo.png"
            alt="Cross Coaching Logo"
            width={500}
            height={80}
            priority
          />
        </div>
        <div className={styles.description}>
          <div>
            <Button type="submit" variant="outlined" onClick={handleLogout}>
              ログアウト
            </Button>
          </div>
        </div>
      </main>
    </>
  )
}
