import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from "next/link"
import Header from "../components/header"

export default function Home() {
  return (
    <>
      <Head>
        <title>Cross Coaching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            src="/crosscoaching_white_logo.png"
            alt="Cross Coaching Logo"
            width={500}
            height={80}
            priority
          />
        </div>
        <div>
          ユーザ登録は
          <Link href={"/signup"}>
            こちら
          </Link>
          から
        </div>
        <div>
          <Link href={"/login"}>
            すでに登録している人はこちら
          </Link>
        </div>
        <div>
          <Link href={"/questions"}>
            コーチングをはじめる
          </Link>
        </div>
        <div>
          <Link href={"/shares"}>
            シェア一覧
          </Link>
        </div>
        <div>
          <Link href={"/feedbacks"}>
            フィードバック一覧
          </Link>
        </div>
      </main>
    </>
  )
}
