import type { NextPage } from 'next'
import React from "react"
import { useRouter } from "next/router"
import Head from 'next/head'
import styles from '@/styles/top.module.css'
import Image from 'next/image'
import Link from "next/link"
import { Button } from "@mui/material"

const Top: NextPage = () => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Cross Coaching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
        <div className="flex flex-col justify-center items-center h-screen">
          <Image
            src="/crosscoaching_white_logo.png"
            alt="Cross Coaching Logo"
            width={500}
            height={80}
            priority
          />
          <div className="text-3xl">
            <Link href={"/login"} className="text-white">
              Login
            </Link>
          </div>
          <div className="text-3xl">
            <Link href={"/signup"} className="text-white">
              Sign up
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}

export default Top
